### ISSUE TITLE
两处勘误

### ISSUE THREAD

**Issue by cvley** [tobegit3hub/ceph_from_scratch#1]
-  [Crush详解](https://github.com/tobegit3hub/ceph_from_scratch/blob/master/architecture/crush.md)中的“算法基础”那一部分的第三段中的“**每个rules吧澳航一系列操作**”；
- [基础组件](https://github.com/tobegit3hub/ceph_from_scratch/blob/master/introduction/component.md)中的“**PG全称Placement Grouop**”应为“Groups”。

Thanks for sharing :smiley:

**Comment by tobegit3hub** [comment]
Thanks for reporting @shwley  :+1:
